In [22]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
glassdata = pd.read_csv('./glass.csv')
print(glassdata)
print(np.unique(glassdata['Type']))
# Notice that in the description, it has 1-7 types, but the dataset does not have Type 4

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]
[1 2 3 5 6 7]


In [23]:
X=glassdata.iloc[:,:-1].values
y=glassdata.iloc[:,-1].values

In [24]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
#from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=0)
pipe = Pipeline([('scaler', StandardScaler()), ('svc', SVC())])
# The pipeline can be used as any other estimator
# and avoids leaking the test set into the train set
pipe.fit(X_train, y_train)
# find accuracy
pipe.fit(X_train, y_train).score(X_test, y_test)

0.7037037037037037

In [25]:
from sklearn.metrics import classification_report

# Make predictions on the test set
y_pred = pipe.predict(X_test)

# Generate the classification report
report = classification_report(y_test, y_pred)

# Print the classification report
print("Classification Report:\n", report)

Classification Report:
               precision    recall  f1-score   support

           1       0.56      0.71      0.63        14
           2       0.69      0.75      0.72        24
           3       0.00      0.00      0.00         5
           5       1.00      1.00      1.00         2
           6       1.00      0.50      0.67         2
           7       1.00      1.00      1.00         7

    accuracy                           0.70        54
   macro avg       0.71      0.66      0.67        54
weighted avg       0.66      0.70      0.67        54



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [26]:
x_input=[[ 1.42101,  12.64,  4.40,  1.10,  71.78 , 0.06 , 8.75, 0.0, 0.0]]
Y_output=pipe.predict(x_input)
print(Y_output)

[2]


https://www.oreilly.com/library/view/python-end-to-end-data/9781788394697/ch18s03.html

In [27]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
y_pred=neigh.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))


from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))


0.6296296296296297
[[10  3  1  0  0  0]
 [ 8 15  0  0  1  0]
 [ 5  0  0  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  1  1]
 [ 1  0  0  0  0  6]]


In [29]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))


from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

0.46296296296296297
[[ 9  3  1  0  1  0]
 [17  5  1  1  0  0]
 [ 2  1  2  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  7]]


In [31]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)

In [32]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))


from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

0.5925925925925926
[[10  2  1  0  1  0]
 [ 5 13  4  1  1  0]
 [ 2  2  1  0  0  0]
 [ 0  1  0  1  0  0]
 [ 0  1  0  0  1  0]
 [ 0  0  0  1  0  6]]
